microstrain_inertial_driver:
  ros__parameters:
    port : '/dev/ttyACM0'
    baudrate : 115200

    # Convert NED to ENU for ROS2 standard
    use_enu_frame : True

    # Frame ID
    frame_id : 'imu_link'

    # Disable PPS (no PPS source available)
    filter_pps_source : 0

    # Filter configuration
    filter_declination_source : 1

    # Enable gyro bias estimation
    filter_enable_gyro_bias_estimation : True

    # Enable filter data streaming
    filter_data_rate: 100
    filter_enable_ahrs: True

    # Filter output data rates
    filter_human_readable_status_data_rate: 1
    filter_odometry_earth_data_rate: 50
    filter_odometry_map_data_rate: 50

    # Filter initialization
    filter_auto_init: True
    filter_reset_after_config: True

    # Heading source (must be 0 for AR models)
    filter_heading_source: 0

    # Publish filter outputs
    publish_filter: True
